name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.6']
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]
        python-version: ["3.8.6"]
    env:
      PYTHON: Conda
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@master
