name: Run tests

on:
  push:
    paths:
    - '**.jl'
  pull_request:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.4']
        julia-arch: [x64]
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v1.0.0
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: julia-actions/julia-runtest@master
      - name: Create Test Badge
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.FLOWFARMTESTSECRET}}
          gistID: <85c89303da1343dbbcce75b746ee30ab>
          filename: test.json
          label: Test
          message: Message
          color: green